name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hemllo! Thanks for filing your first issue to the token. Please make sure that you have read the guidelines before reporting the issue (upcoming) and follow the templates. Thamnks!'
        pr-message: 'Hemllo! Thanks for filing your first PR to the token. Please make sure that you have read the guidelines before filing and using the templates (upcoming). Thamnks!'
